# Generated by Django 5.0.2 on 2025-07-24 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
